### ISSUE TITLE
Release v0.1.1 crashing

### ISSUE THREAD

**Issue by medonja** [NUMde/compass-numapp-frontend#146]
It seems that the v0.1.1 release introduces a new problem, which makes the app crash on Android:
The provided demo APK crashes as well.

Caused by: java.lang.UnsupportedOperationException: Your application is configured to use RNGestureHandlerEnabledRootView which is no longer supported. You can see how to migrate to <GestureHandlerRootView /> here: https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.<init>(RNGestureHandlerEnabledRootView.kt:17)
        at de.num.ukbumfragetool.android.MainActivity$1.createRootView(MainActivity.java:29)
        at com.facebook.react.ReactActivityDelegate$1.createRootView(ReactActivityDelegate.java:82)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:102)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:86)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
        at de.num.ukbumfragetool.android.MainActivity.onCreate(MainActivity.java:37)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by mbastian93** [comment]
I'm already on it; #156 will fix it
